### PR TITLE
Add cx,cy to specify crop coordinate.

### PR DESCRIPTION
**Pull request by osamunmun**
- specify crop start coordinate 
  - (0, 0) is center of image, and cx, cy represent coordinate based on (0, 0)
  - ex: cx=50 mean crop image center is 50pixel right from center of original image.(minus is left)
  - ex: cy=30 mean crop image center is 30pixel up from center of original image.(minus is down)

### CODE REVIEW

**Comment by osamunmun** [comment]
sorry, the calc coordinate logic is wrong, and I fixed it. https://github.com/cubicdaiya/ngx_small_light/pull/49/commits/502d346665db2a2da8e401d56c62599ed9e77017

**Comment by cubicdaiya** [comment]
This PR looks very complicated for me. Why is the parameters such as `sx`, `sy`, `dx`, `dy`?

**Comment by osamunmun** [comment]
img_1399

Surely it's complicated. I attached sample image, and describe some var definitions(dx,dw....)

#### definitions
- dh, dw
  - In this case, dh and dw are original image height and width
- ch, cw
  - crop height and width
- dx,dy
  - distance from at the upper left of original image to at the upper left of crop image
- x0,y0
  - center coordinate of original image
- cx,cy
  - distance from x0, y0

#### how to calculate
```
x0 = dw/2, y0=dh/2
dx + cw/2 = x0 + cx
dx + cw/2 = dw/2 + cx
dx = cx + dw/2 - cw/2
```

For example, 
- orignal image size(dw=600, dh=300)
- crop image size(cw=300, ch=300)
- crop coordinate(cx=150, ch=0)

```
dx = 150 + 600/2 - 300/2
     =  300
```

But plus mean toward the left, it cloud be better given plus param mean toward the right.
So I reversal sign.

```
dx = -cx - dw/2 + cw/2
```

dy is also same logic.

It's hard to explain...

Or just specifying distance from at the upper left with cx and cy is easy to understand?

**Comment by cubicdaiya** [comment]
Though the calculation is maybe required when the URL is generated, use `sx` and `sy` in this case. At least for now I'm not positive to add such feature to ngx_small_light. Because it is very complicated to use canvas for cropping partially. If such feature is added, it should be implemented without canvas.

**Comment by osamunmun** [comment]
I agree using `sx` and `sy`. 
I tried using `sx` and `sy`, but it doesn't work well.
I guess that code below is coresopnding location.

ngx_small_light_imagemagick.c 
```
p = ngx_snprintf(crop_geo, sizeof(crop_geo) - 1, "%f!x%f!+%f+%f", sz.sw, sz.sh, sz.sx, sz.sy);
```

The result is different from `convert -crop 600x338+50+0 test.jpg crop_test_600x338+50+0.jpg`, result on local imagemagick cmd.
Cropped image by ngx_small_light is zoomed and crop base coordinate looks at upper left.
I couldn't resolve this behavior.

**Pull request closed without merging**
