### PR TITLE
Add webp source image support

### PR DESCRIPTION
**Pull request by cgs3238**
Add webp source image support

### CODE REVIEW

**Comment by cubicdaiya** [comment]
Thank you for your PR. I'll review in this weekend.

**Comment by cubicdaiya** [comment]
Hi @cgs3238 ,

As I commented about your changes, please check it.

**Comment by cgs3238** [comment]
Thanks for your advices.
I formatted the code, please have a look.

**Comment by cubicdaiya** [comment]
Hi @cgs3238,

Though I looked latest changes, it seems to be broken or leaked changes?

**Comment by cgs3238** [comment]
So strange...... Recommitted.

**Comment by cubicdaiya** [comment]
commited, thanks.

**Pull request merged**
